# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: false
  keep_last_epochs: 5

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: valid,assamese_valid,bodo_valid,gujarati_valid,karbi_valid,ladakhi_valid,marathi_valid,pahari_valid,santali_valid,urdu_valid,balti_valid,chhatisgar_valid,hindi_valid,kashmiri_valid,lepcha_valid,mizo_valid,punjabi_valid,sindhi_valid,bengali_valid,dogri_valid,indian_english_valid,khasi_valid,maithili_valid,nagamese_valid,rajasthani_valid,tamil_valid,bhojpuri_valid,garo_valid,jaintia_valid,kokborok_valid,malayalam_valid,nepali_valid,sambalpuri_valid,telugu_valid,bhutia_valid,gojri_valid,kannada_valid,konkani_valid,manipuri_valid,odia_valid,sanskrit_valid

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity", "code_perplexity", "temp"]
  loss_weights: [0.1, 10]

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
