# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: false
  keep_last_epochs: 5

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 6
  max_tokens: 1200000
  skip_invalid_size_inputs_valid_test: true
  train_subset: assamese_train,bodo_train,gujarati_train,karbi_train,ladakhi_train,marathi_train,pahari_train,santali_train,urdu_train,balti_train,chhatisgar_train,hindi_train,kashmiri_train,lepcha_train,mizo_train,punjabi_train,sindhi_train,bengali_train,dogri_train,indian_english_train,khasi_train,maithili_train,nagamese_train,rajasthani_train,tamil_train,bhojpuri_train,garo_train,jaintia_train,kokborok_train,malayalam_train,nepali_train,sambalpuri_train,telugu_train,bhutia_train,gojri_train,kannada_train,konkani_train,manipuri_train,odia_train,sanskrit_train
  valid_subset: valid,assamese_valid,bodo_valid,gujarati_valid,karbi_valid,ladakhi_valid,marathi_valid,pahari_valid,santali_valid,urdu_valid,balti_valid,chhatisgar_valid,hindi_valid,kashmiri_valid,lepcha_valid,mizo_valid,punjabi_valid,sindhi_valid,bengali_valid,dogri_valid,indian_english_valid,khasi_valid,maithili_valid,nagamese_valid,rajasthani_valid,tamil_valid,bhojpuri_valid,garo_valid,jaintia_valid,kokborok_valid,malayalam_valid,nepali_valid,sambalpuri_valid,telugu_valid,bhutia_valid,gojri_valid,kannada_valid,konkani_valid,manipuri_valid,odia_valid,sanskrit_valid
distributed_training:
  distributed_world_size: 128
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity", "code_perplexity", "temp"]
  loss_weights: [0.1, 0]

optimization:
  max_update: 1000000
  lr: [0.005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  quantize_targets: true
  extractor_mode: layer_norm
  layer_norm_first: true
  final_dim: 768
  latent_temp: [2.0, 0.1, 0.999995]
  encoder_layerdrop: 0.00
  dropout_input: 0.0
  dropout_features: 0.0
  dropout: 0.0
  attention_dropout: 0.0
  conv_bias: true

  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16

  feature_grad_mult: 1.0
